# Generated by Django 4.1.5 on 2023-02-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_avatar',
            field=models.ImageField(null=True, upload_to='songs_affiches/'),
        ),
    ]
