# Generated by Django 4.1.5 on 2023-02-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_song_song_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(null=True, upload_to='songs_files/'),
        ),
    ]
