# Generated by Django 4.1.5 on 2023-02-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_avatar',
            field=models.ImageField(null=True, upload_to='playlist_images/'),
        ),
    ]
